[env]
TERM = "xterm-256color"
[general]
live_config_reload = true
import = [ "./theme.toml" ]
[window]
decorations_theme_variant = "Dark"
[font]
# good for daily use
# normal = { family = "VictorMono Nerd Font Mono", style = "Medium" }
# bold = { family = "VictorMono Nerd Font Mono", style = "Bold" }
# italic = { family = "Maple Mono NF", style = "Regular" }
# bold_italic = { family = "Maple Mono NF", style = "Bold Italic" }
# size = 14
# offset = { x = 0, y = -5 }
# nice font
normal = { family = "Perfect Dos Vga 437 Win", style = "Regular" }
